version: '3.8'

services:
 web:
  #command: python manage.py runserver 0.0.0.0:8000
  build:
   context: .
  ports:
   - 8000:8000
   - 9922:22
  volumes:
   - ./:/app
  networks:
    - webnet
 redis_jarvis:
  command: bash -c "redis-server --save 10 1 --requirepass 8hd8293hd92"
  image: redis
  ports:
    - 6379:6379
  volumes:
    - ~/docker_volumes/redis-data:/data
  networks:
    - webnet

networks:
  webnet: