# Generated by Django 5.1.7 on 2025-03-20 14:23

import binascii
import os

from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_initial_user(apps, schema_editor):
    # Get the User model from the migration state
    User = apps.get_model("auth", "User")

    # Skip if any users exist
    if User.objects.exists():
        return

    # Create admin user
    admin = User.objects.create(
        username="admin",
        email="admin@example.com",
        password=make_password("admin"),
        is_staff=True,
        is_superuser=True,
        is_active=True,
    )

    # Create auth token for the user with valid key
    Token = apps.get_model("authtoken", "Token")
    # Generate a random token key (same method as DRF's Token model)
    key = binascii.hexlify(os.urandom(20)).decode()
    token = Token.objects.create(user=admin, key=key)

    print("Initial admin user created successfully with credentials:")
    print("Username: admin")
    print("Password: admin")
    print(f"Token: {token.key}")


def delete_initial_user(apps, schema_editor):
    # Reverse operation - delete the admin user if needed
    User = apps.get_model("auth", "User")
    User.objects.filter(username="admin").delete()


class Migration(migrations.Migration):

    dependencies = [
        (
            "auth",
            "0012_alter_user_first_name_max_length",
        ),  # Ensure auth migrations have run
        ("authtoken", "0001_initial"),  # Ensure authtoken migrations have run
    ]

    operations = [
        migrations.RunPython(create_initial_user, delete_initial_user),
    ]
