# Generated by Django 5.1.7 on 2025-03-20 14:55

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_create_initial_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserKnowledgeBase",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "topics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Topics the user is interested in",
                    ),
                ),
                (
                    "preferences",
                    models.JSONField(
                        blank=True, default=dict, help_text="User preferences"
                    ),
                ),
                (
                    "knowledge_text",
                    models.TextField(
                        blank=True,
                        help_text="AI-maintained knowledge about the user in a structured format",
                    ),
                ),
                (
                    "last_analyzed_message_id",
                    models.UUIDField(
                        blank=True,
                        help_text="ID of the last message that was analyzed to update this knowledge base",
                        null=True,
                    ),
                ),
                (
                    "knowledge_version",
                    models.IntegerField(
                        default=1,
                        help_text="Version of the knowledge structure, for tracking schema changes",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_base",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Knowledge Base",
                "verbose_name_plural": "User Knowledge Bases",
                "indexes": [
                    models.Index(
                        fields=["user"], name="core_userkn_user_id_7442be_idx"
                    ),
                    models.Index(
                        fields=["updated_at"], name="core_userkn_updated_182a2d_idx"
                    ),
                ],
            },
        ),
    ]
