# Generated by Django 5.1.7 on 2025-03-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userknowledgebase",
            name="version",
            field=models.FloatField(default=1.0),
        ),
    ]
