# Generated by Django 5.1.7 on 2025-03-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_userknowledgebase_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userknowledgebase",
            name="version",
            field=models.DecimalField(
                decimal_places=1,
                default=1.0,
                help_text="Version number for tracking knowledge base updates",
                max_digits=3,
            ),
        ),
    ]
