# Generated by Django 5.1.7 on 2025-03-20 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_userknowledgebase_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userknowledgebase",
            name="preferences",
        ),
        migrations.AlterField(
            model_name="userknowledgebase",
            name="topics",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Ranked topics the user is interested in. Format: {'topics': [{'name': 'AI', 'description': 'Strong interest in artificial intelligence and machine learning', 'rank': 0.95}, {'name': 'Art', 'description': 'Digital art and generative AI art creation', 'rank': 0.8}]}",
            ),
        ),
    ]
