# Generated by Django 5.1.7 on 2025-04-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_userknowledgebase_preferences_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserKnowledgeBase",
        ),
    ]
