# Generated by Django 4.1.4 on 2022-12-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epguide_name', models.CharField(max_length=250)),
                ('full_name', models.CharField(max_length=250)),
                ('current_season', models.IntegerField()),
                ('current_episode', models.IntegerField()),
            ],
        ),
    ]
