# Generated by Django 4.1.4 on 2023-03-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_mediafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='last_read_from_disk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
