# Generated by Django 4.1.4 on 2023-03-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_alter_mediafile_last_read_from_disk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='keep',
            field=models.BooleanField(default=False),
        ),
    ]
