# Generated by Django 5.1.7 on 2025-03-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
