# Generated by Django 5.1.7 on 2025-03-19 11:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_message_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversation",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="message",
            name="edited_at",
        ),
        migrations.AlterField(
            model_name="conversation",
            name="title",
            field=models.CharField(default="New conversation", max_length=255),
        ),
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "User"),
                    ("assistant", "Assistant"),
                    ("system", "System"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["-updated_at"], name="chat_conver_updated_1f6ffe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "-updated_at"], name="chat_conver_user_id_e2a76b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["user", "is_archived", "-updated_at"],
                name="chat_conver_user_id_c830f5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="chat_messag_convers_3154fc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "is_deleted", "created_at"],
                name="chat_messag_convers_ecc067_idx",
            ),
        ),
    ]
