# Generated by Django 5.1.7 on 2025-04-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_remove_conversation_is_deleted_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="message",
            name="chat_messag_convers_ecc067_idx",
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="message",
            name="is_edited",
        ),
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("agent", "Agent")], max_length=10
            ),
        ),
    ]
