# Generated by Django 5.1.7 on 2025-04-05 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_remove_message_chat_messag_convers_ecc067_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="conversation",
            name="chat_conver_user_id_c830f5_idx",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="is_archived",
        ),
    ]
