# Generated by Django 5.1.7 on 2025-04-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_remove_conversation_chat_conver_user_id_c830f5_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_generating",
            field=models.BooleanField(default=False),
        ),
    ]
