# Generated by Django 5.1.7 on 2025-04-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_message_is_generating"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="status_generating",
            field=models.CharField(
                blank=True,
                help_text="Current generation status (e.g., 'Thinking', 'Browsing')",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(max_length=50),
        ),
    ]
