# Generated by Django 5.1.7 on 2025-04-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_message_status_generating_alter_message_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="role",
            field=models.CharField(
                choices=[("user", "User"), ("agent", "Agent")], max_length=50
            ),
        ),
    ]
