# Generated by Django 5.1.7 on 2025-04-06 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_alter_message_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="status_generating",
            field=models.CharField(
                default="Thinking",
                help_text="Current generation status (e.g., 'Thinking', 'Browsing')",
                max_length=255,
            ),
        ),
    ]
