# Generated by Django 5.1.7 on 2025-11-30 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_alter_message_role_memory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="memory",
            options={
                "verbose_name": "User Memory Profile",
                "verbose_name_plural": "User Memory Profiles",
            },
        ),
        migrations.RemoveField(
            model_name="memory",
            name="content",
        ),
        migrations.AddField(
            model_name="memory",
            name="data",
            field=models.JSONField(
                default=dict,
                help_text="Structured user profile data (e.g., {'personal': ..., 'interests': ...})",
            ),
        ),
        migrations.AlterField(
            model_name="memory",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="memory",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
