# Generated by Django 5.1.7 on 2025-11-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0013_alter_memory_options_remove_memory_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="summary",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Auto-generated summary of the conversation content",
            ),
        ),
    ]
