# Generated by Django 4.1.4 on 2022-12-23 20:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_tvshow_last_release_date_tvshow_last_release_episode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='current_episode',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='current_season',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='datetime_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='datetime_edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tvshow',
            name='downloaded_current_episode',
            field=models.BooleanField(default=False),
        ),
    ]
