# Generated by Django 4.1.4 on 2023-03-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0007_mediafile_keep'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='is_movie',
            field=models.BooleanField(default=False),
        ),
    ]
