# Generated by Django 4.1.4 on 2025-03-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0008_mediafile_is_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediafile',
            name='renamed_from',
            field=models.TextField(default='', verbose_name=''),
        ),
    ]
