# Generated by Django 4.1.4 on 2025-03-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shows", "0009_mediafile_renamed_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="renamed_from",
            field=models.TextField(blank=True, null=True),
        ),
    ]
