# Generated by Django 5.1.7 on 2025-03-16 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shows", "0010_alter_mediafile_renamed_from"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tvshow",
            options={"ordering": ["full_name"]},
        ),
        migrations.AddField(
            model_name="mediafile",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="tvshow",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="path",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
