# Generated by Django 5.1.7 on 2025-03-16 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("path", models.CharField(max_length=255, unique=True)),
                ("dirname", models.CharField(max_length=255)),
                ("ext", models.CharField(max_length=10)),
                ("st_mode", models.IntegerField(blank=True, null=True)),
                ("st_uid", models.IntegerField(blank=True, null=True)),
                ("st_gid", models.IntegerField(blank=True, null=True)),
                ("st_size", models.IntegerField(blank=True, null=True)),
                ("st_atime", models.FloatField(blank=True, null=True)),
                ("st_mtime", models.FloatField(blank=True, null=True)),
                ("st_ctime", models.FloatField(blank=True, null=True)),
                ("last_read_from_disk", models.DateTimeField(blank=True, null=True)),
                ("keep", models.BooleanField(default=False)),
                ("is_movie", models.BooleanField(default=False)),
                (
                    "renamed_from",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TVShow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("epguide_name", models.CharField(max_length=255, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("current_season", models.IntegerField(default=1)),
                ("current_episode", models.IntegerField(default=1)),
                ("active", models.BooleanField(default=False)),
                ("keep", models.BooleanField(default=False)),
                ("datetime_edited", models.DateTimeField(auto_now=True)),
                ("datetime_added", models.DateTimeField(auto_now_add=True)),
                ("downloaded_current_episode", models.BooleanField(default=False)),
                (
                    "episode_lookup_type",
                    models.CharField(default="epguides", max_length=32),
                ),
                ("first_release_date", models.DateTimeField(blank=True, null=True)),
                ("last_release_date", models.DateTimeField(blank=True, null=True)),
                ("last_release_season", models.IntegerField(blank=True, null=True)),
                ("last_release_episode", models.IntegerField(blank=True, null=True)),
                ("next_release_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
    ]
